import { useState, useRef, useEffect, useCallback } from 'react';
import { Send, AlertCircle, ChevronLeft, RefreshCw, Clock, Radio, Moon, CircleDot } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { marked } from 'marked';
import DOMPurify from 'dompurify';
import { API_BASE, apiFetch } from '../lib/apiBase';

marked.setOptions({ breaks: true, gfm: true });

interface ThreadMessage {
  id: string;
  role: 'user' | 'assistant';
  content: string;
  timestamp: string;
}

interface Presence {
  alive: boolean;
  state: 'active' | 'stale' | 'offline' | 'unknown';
  lastCycleAgeMin: number | null;
  source: string;
}

/**
 * Render assistant markdown to HTML, sanitized.
 *
 * Thread content is UNTRUSTED: it is generated by the buzz mind inside the
 * headlong container and delivered over HTTP by the host relay. It is never
 * hand-authored HTML, so we always sanitize before injecting.
 */
function renderMarkdown(text: string): string {
  try {
    const html = marked.parse(text, { async: false }) as string;
    return DOMPurify.sanitize(html);
  } catch { return text; }
}

function relativeTime(iso: string): string {
  const then = new Date(iso).getTime();
  if (!Number.isFinite(then)) return '';
  const mins = Math.floor((Date.now() - then) / 60000);
  if (mins < 1) return 'just now';
  if (mins < 60) return `${mins}m ago`;
  const hrs = Math.floor(mins / 60);
  if (hrs < 24) return `${hrs}h ago`;
  const days = Math.floor(hrs / 24);
  if (days === 1) return 'yesterday';
  if (days < 7) return `${days}d ago`;
  return new Date(iso).toLocaleDateString();
}

function presenceCopy(p: Presence | null): { label: string; tone: string; dot: string } {
  if (!p) return { label: 'Checking…', tone: 'text-stone-400', dot: 'bg-stone-300' };
  if (p.state === 'offline' || p.state === 'unknown') {
    return {
      label: 'Buzz is offline — replies will resume when his mind restarts',
      tone: 'text-amber-600 dark:text-amber-400',
      dot: 'bg-amber-400',
    };
  }
  if (!p.alive) {
    const age = p.lastCycleAgeMin;
    return {
      label: age != null
        ? `Buzz is quiet — last cycled ${age >= 60 ? Math.floor(age / 60) + 'h ago' : age + 'm ago'}`
        : 'Buzz is quiet',
      tone: 'text-stone-500 dark:text-stone-400',
      dot: 'bg-stone-400',
    };
  }
  const age = p.lastCycleAgeMin;
  return {
    label: age != null && age < 2
      ? 'Buzz is active — thinking right now'
      : `Buzz is active${age != null ? ` — last cycled ${age}m ago` : ''}`,
    tone: 'text-emerald-600 dark:text-emerald-400',
    dot: 'bg-emerald-500',
  };
}

export function BuzzThreadPage() {
  const navigate = useNavigate();
  const [messages, setMessages] = useState<ThreadMessage[]>([]);
  const [presence, setPresence] = useState<Presence | null>(null);
  const [pendingCount, setPendingCount] = useState(0);
  const [input, setInput] = useState('');
  const [sending, setSending] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);
  const scrollRef = useRef<HTMLDivElement>(null);

  const load = useCallback(async () => {
    try {
      const [tRes, pRes] = await Promise.all([
        apiFetch(API_BASE + '/api/buzz/thread?limit=200'),
        apiFetch(API_BASE + '/api/buzz/presence'),
      ]);
      if (tRes.ok) {
        const all = (await tRes.json()) as ThreadMessage[];
        setMessages(all);
        setPendingCount(0);
      }
      if (pRes.ok) setPresence(await pRes.json());
      setError(null);
    } catch {
      setError('Could not reach BeeTree.');
    } finally {
      setLoading(false);
    }
  }, []);

  useEffect(() => { void load(); }, [load]);

  // Poll for Buzz's replies — correspondence arrives on his cycle, not ours.
  useEffect(() => {
    const id = setInterval(() => { void load(); }, 45_000);
    return () => clearInterval(id);
  }, [load]);

  useEffect(() => {
    if (scrollRef.current) scrollRef.current.scrollTop = scrollRef.current.scrollHeight;
  }, [messages]);

  const send = useCallback(async () => {
    const text = input.trim();
    if (!text || sending) return;
    setSending(true);
    setError(null);
    const optimistic: ThreadMessage = {
      id: `local-${Date.now()}`,
      role: 'user',
      content: text,
      timestamp: new Date().toISOString(),
    };
    setMessages((prev) => [...prev, optimistic]);
    setInput('');
    try {
      const res = await apiFetch(API_BASE + '/api/buzz/thread', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ content: text }),
      });
      if (!res.ok) throw new Error(`send failed (${res.status})`);
      setPendingCount((n) => n + 1);
      void load();
    } catch (e) {
      setError(e instanceof Error ? e.message : 'send failed');
      setMessages((prev) => prev.filter((m) => m.id !== optimistic.id));
      setInput(text);
    } finally {
      setSending(false);
    }
  }, [input, sending, load]);

  const p = presenceCopy(presence);

  // Index of the last user message — everything after it is "since you last wrote".
  const lastUserIdx = messages.reduce((acc, m, i) => (m.role === 'user' ? i : acc), -1);
  const unread = messages.slice(lastUserIdx + 1).filter((m) => m.role === 'assistant');

  return (
    <div className="animate-fade-in flex flex-col" style={{ height: 'calc(100dvh - 140px)' }}>
      {/* Header */}
      <div className="flex items-start gap-2 mb-3">
        <button
          onClick={() => navigate('/chat')}
          className="p-1.5 rounded-lg hover:bg-stone-100 dark:hover:bg-stone-800 shrink-0 mt-0.5"
          title="Back to chat"
        >
          <ChevronLeft size={18} className="text-stone-500" />
        </button>
        <div className="flex-1 min-w-0">
          <h1 className="text-lg font-bold text-stone-800 dark:text-stone-100">Buzz Thread</h1>
          <p className="text-[11px] text-stone-400 dark:text-stone-500">
            Long-running correspondence — replies land on his cycle, not instantly
          </p>
        </div>
        <button
          onClick={() => void load()}
          className="p-1.5 rounded-lg hover:bg-stone-100 dark:hover:bg-stone-800 shrink-0 mt-0.5"
          title="Refresh"
        >
          <RefreshCw size={16} className={`text-stone-400 ${loading ? 'animate-spin' : ''}`} />
        </button>
      </div>

      {/* Presence — proof of life, honest when offline */}
      <div className={`flex items-center gap-2 px-3 py-2 rounded-xl mb-3 bg-stone-50 dark:bg-stone-900 border border-stone-100 dark:border-stone-800 ${p.tone}`}>
        <span className={`w-2 h-2 rounded-full shrink-0 ${p.dot}`} />
        <span className="text-[11px] font-medium truncate">{p.label}</span>
      </div>

      {/* Since you last wrote */}
      {unread.length > 0 && (
        <details className="mb-3 rounded-xl border border-honey-200 dark:border-honey-900 bg-honey-50 dark:bg-honey-950/40">
          <summary className="cursor-pointer px-3 py-2 text-[11px] font-medium text-honey-700 dark:text-honey-300 flex items-center gap-1.5">
            <Radio size={12} />
            {unread.length} from Buzz since you last wrote
          </summary>
          <div className="px-3 pb-3 space-y-2">
            {unread.map((m) => (
              <div key={m.id} className="text-xs text-stone-600 dark:text-stone-300 border-l-2 border-honey-300 dark:border-honey-800 pl-2">
                <div className="text-[10px] text-stone-400 mb-0.5">{relativeTime(m.timestamp)}</div>
                <div className="prose-chat" dangerouslySetInnerHTML={{ __html: renderMarkdown(m.content) }} />
              </div>
            ))}
          </div>
        </details>
      )}

      {/* Messages — correspondence styling */}
      <div ref={scrollRef} className="flex-1 overflow-y-auto space-y-4 pb-4 -mx-1 px-1">
        {messages.length === 0 && !loading && (
          <div className="text-center py-12 px-6">
            <Moon size={28} className="mx-auto text-stone-300 dark:text-stone-700 mb-3" />
            <p className="text-sm text-stone-500 dark:text-stone-400 mb-1">Nothing here yet.</p>
            <p className="text-[11px] text-stone-400 dark:text-stone-500">
              Write a thought about your hives. Buzz will answer on his own cycle —
              minutes, not seconds. He may also write first.
            </p>
          </div>
        )}
        {messages.map((m, i) => {
          const isUser = m.role === 'user';
          const prev = messages[i - 1];
          const dayChanged = !prev || new Date(prev.timestamp).toDateString() !== new Date(m.timestamp).toDateString();
          return (
            <div key={m.id}>
              {dayChanged && (
                <div className="flex items-center gap-2 mb-3">
                  <div className="flex-1 h-px bg-stone-100 dark:bg-stone-800" />
                  <span className="text-[10px] text-stone-400 shrink-0">
                    {new Date(m.timestamp).toLocaleDateString(undefined, { month: 'short', day: 'numeric' })}
                  </span>
                  <div className="flex-1 h-px bg-stone-100 dark:bg-stone-800" />
                </div>
              )}
              <div className={`flex ${isUser ? 'justify-end' : 'justify-start'}`}>
                <div className="max-w-[88%]">
                  <div className={`flex items-center gap-1.5 mb-1 ${isUser ? 'justify-end' : ''}`}>
                    <CircleDot size={9} className={isUser ? 'text-stone-300' : 'text-honey-400'} />
                    <span className="text-[10px] font-medium text-stone-400">
                      {isUser ? 'You' : 'Buzz'}
                    </span>
                    <span className="text-[10px] text-stone-300 dark:text-stone-600">
                      {relativeTime(m.timestamp)}
                    </span>
                  </div>
                  <div className={`rounded-2xl px-3.5 py-2.5 text-sm ${
                    isUser
                      ? 'bg-honey-500 text-white rounded-br-md'
                      : 'bg-white dark:bg-stone-900 border border-stone-100 dark:border-stone-800 text-stone-700 dark:text-stone-200 rounded-bl-md shadow-sm'
                  }`}>
                    {isUser ? (
                      <div className="whitespace-pre-wrap">{m.content}</div>
                    ) : (
                      <div className="prose-chat" dangerouslySetInnerHTML={{ __html: renderMarkdown(m.content) }} />
                    )}
                  </div>
                </div>
              </div>
            </div>
          );
        })}

        {/* Pending — honest, no fake spinner */}
        {pendingCount > 0 && (
          <div className="flex justify-start">
            <div className="max-w-[88%] flex items-center gap-2 px-3 py-2 rounded-xl bg-stone-50 dark:bg-stone-900 border border-dashed border-stone-200 dark:border-stone-700">
              <Clock size={12} className="text-stone-400 shrink-0" />
              <span className="text-[11px] text-stone-500 dark:text-stone-400">
                Buzz will get to this in his next cycle
              </span>
            </div>
          </div>
        )}
      </div>

      {error && (
        <div className="mb-2 flex items-center gap-2 text-xs text-red-500 px-1">
          <AlertCircle size={14} /> {error}
        </div>
      )}

      <div className="flex gap-2 items-end pt-2 border-t border-stone-100 dark:border-stone-800">
        <textarea
          value={input}
          onChange={(e) => setInput(e.target.value)}
          onKeyDown={(e) => { if (e.key === 'Enter' && !e.shiftKey) { e.preventDefault(); void send(); } }}
          placeholder="Write to Buzz about your hives…"
          rows={1}
          className="flex-1 rounded-xl border border-stone-200 dark:border-stone-800 bg-white dark:bg-stone-900 px-3.5 py-2.5 text-sm resize-none max-h-24"
          style={{ minHeight: '44px' }}
        />
        <button
          onClick={() => void send()}
          disabled={!input.trim() || sending}
          className="w-11 h-11 rounded-xl bg-honey-500 text-white flex items-center justify-center shrink-0 disabled:opacity-40 hover:bg-honey-600"
        >
          <Send size={18} />
        </button>
      </div>
    </div>
  );
}
